name: Flutter-CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unit-test:
    name: Build Testing on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019, macos-10.15]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
         
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.0.0"
          channel: 'stable'
      
      - name: Flutter Upgrade
        run: flutter upgrade
      
      - name: Get dependencies
        run: flutter pub get

      - run: flutter analyze
      - name: Ensure the Dart code is formatted correctly
        run: flutter format --set-exit-if-changed --dry-run .
      - name: Run Flutter unit tests
        run: flutter test
        
      # Runs a set of commands using the runners shell
      - name: Final Build check
        run: flutter build appbundle
