name: Flutter CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: mac-mini-m1
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Decoding Keystore file
        run: echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks

      - name: Pub Get Packages
        run: flutter pub get
        
      - name: build
        run: flutter run
